components:
  responses:
    BadRequest:
      description: Resource not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ZodError"
    NotFound:
      description: Mal formed req body.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AppError"
    EmailAlready:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/EmailAlready"
    LoginNotMatch:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LoginNotMatch"
    TokenRequired:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TokenRequired"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Forbidden"
  schemas:
    UsersCreateReturn:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          example: 227af912-87f0-4cbd-ab6a-d9120e2c2a6b
        name:
          type: string
          example: Jhon Wick
        email:
          type: string
          example: jwparabellum@email.com
    AppError:
      type: object
      properties:
        message:
          type: string
          example: Resource not found.
    EmailAlready:
      type: object
      properties:
        message:
          type: string
          example: E-mail already registered
    ZodError:
      type: object
      properties:
        issues:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: invalid_type
              expected:
                type: string
                example: string
              received:
                type: string
                example: undefined
              path:
                type: array
                items:
                  type: string
                  example: field_name_path
              message:
                type: string
                example: Required
        name:
          type: string
          example: ZodError
    LoginReturn:
      type: object
      properties:
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1NGE1NDk5LTlhNjQtNGRjOS04ZGVmLTBhMTkyZTVjYWZmZiIsImlhdCI6MTcxNTI5OTg5MywiZXhwIjoxNzE1OTA0NjkzfQ.h7f_jbduxm59eVw_MaCkCHJRkq2Hdt0EGTyDdZXmdiU
        user:
          type: object
          properties:
            id:
              type: string
              example: e54a5499-9a64-4dc9-8def-0a192e5cafff
            name:
              type: string
              example: Jhon Wick
            email:
              type: string
              example: jwparabellum@email.com
    LoginNotMatch:
      type: object
      properties:
        error:
          type: string
          example: E-mail and password doesn't match
    ProfileReturn:
      type: object
      properties:
        id:
          type: string
          example: e54a5499-9a64-4dc9-8def-0a192e5cafff
        name:
          type: string
          example: Jhon Wick
        email:
          type: string
          example: jwparabellum@email.com
    TokenRequired:
      type: object
      properties:
        error:
          type: string
          example: Token is required
    Forbidden:
      type: object
      properties:
        error:
          type: string
          example: This user is not the car owner
